require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'bin/**/*'

# Disable problematic Capybara cops (not using Capybara)
Capybara/RSpec/PredicateMatcher:
  Enabled: false

# Gemspec development dependencies are also in Gemfile (intentional)
Gemspec/DevelopmentDependencies:
  Enabled: false

# RSpec file path format - using XCFrameworkCLI namespace
RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

# Style preferences
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# Metrics
Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'
    - '*.gemspec'

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# RSpec
RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

