# frozen_string_literal: true

require 'yaml'
require 'json'

module XCFrameworkCLI
  module Config
    # Generates configuration files from templates
    class Generator
      attr_reader :config

      # Initialize generator with config hash
      #
      # @param config [Hash] Configuration data
      def initialize(config)
        @config = config
      end

      # Convert config to YAML string
      #
      # @return [String] YAML formatted configuration with comments
      def to_yaml
        output = ['# XCFramework build configuration', '# Generated by xckit init', '']

        # Add appropriate comments based on config type
        if config[:spm]
          output << '# Swift Package Manager configuration'
          output << ''
        elsif config[:project]
          output << '# Xcode project configuration'
          output << ''
        end

        # Convert to string-keyed hash for proper YAML output
        string_config = stringify_keys(config)
        output << string_config.to_yaml.lines[1..].join # Skip "---" line
        output.join("\n")
      end

      private

      # Convert symbol keys to strings recursively
      #
      # @param obj [Object] Object to convert
      # @return [Object] Converted object
      def stringify_keys(obj)
        case obj
        when Hash
          obj.each_with_object({}) do |(key, value), hash|
            hash[key.to_s] = stringify_keys(value)
          end
        when Array
          obj.map { |item| stringify_keys(item) }
        else
          obj
        end
      end

      # Convert config to JSON string
      #
      # @return [String] JSON formatted configuration
      def to_json(*_args)
        JSON.pretty_generate(stringify_keys(config))
      end

      class << self
        # Generate SPM config template
        #
        # @param targets [Array<String>] Library targets
        # @param platforms [Hash] Platform versions
        # @param version [String, nil] Minimum platform version
        # @return [Hash] SPM configuration hash
        def spm_template(targets:, platforms:, version: nil)
          # Detect minimum iOS version from platforms
          ios_version = version || platforms['ios'] || '15.0'

          {
            spm: {
              package_dir: '.',
              targets: targets,
              platforms: %w[ios ios-simulator],
              library_evolution: true,
              version: ios_version
            },
            build: {
              output_dir: './build',
              configuration: 'Release',
              verbose: false
            }
          }
        end

        # Generate Xcode project config template
        #
        # @param project_path [String] Path to .xcodeproj or .xcworkspace
        # @param scheme [String] Scheme name
        # @param framework_name [String] Framework name
        # @param platforms [Array<String>] Target platforms
        # @return [Hash] Xcode configuration hash
        def xcode_template(project_path:, scheme:, framework_name:, platforms: %w[ios ios-simulator])
          {
            project: {
              name: framework_name,
              xcode_project: project_path
            },
            frameworks: [
              {
                name: framework_name,
                scheme: scheme,
                platforms: platforms
              }
            ],
            build: {
              configuration: 'Release',
              output_dir: './build',
              clean: true,
              debug_symbols: true
            }
          }
        end
      end
    end
  end
end
